services:
  mongo:
    image: mongo
    restart: always
    environment:
    #   MONGO_INITDB_ROOT_USERNAME: root 
    #   MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: userdb
    ports:
      - '27017:27017'
    volumes:
      - ./dbdata:/data/db
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    volumes:
      - ./cache:/data
  
